version: '3.3'
volumes:
  'sql03-virtdbnx-asp':
    driver: nimble
    driver_opts:
      importVolAsClone: sql03-virtdbnx-asp
      forceImport: "true"
services:
  virtdbnx:
    image: tmeregistry.azurecr.io/virtdbnx-asp
    build:
      context: .
      dockerfile: Dockerfile_virtdbnx
    depends_on:
      - db
    ports:
      - '50938:80'
      - '2222:2222'
  db:
    image: tmeregistry.azurecr.io/virtdbnx-asp-db
    build:
      context: .
      dockerfile: Dockerfile_virtdbnx_db
    environment:
      SA_PASSWORD: "My_P@ssw0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - '1410:1433'
    volumes:
      - sql03-virtdbnx-asp:/var/opt/mssql/sqldata/udb
